language: generic
sudo: required # having super-user permissions
services:
  - docker

before_install:
  - docker build -t walkindead/docker-react -f Dockerfile.dev .

script:
  # to exit the 'npm run test' after finishing,  -- --coverage
  - docker run -e CI=true walkindead/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-610867789039" # automatically generates when you create elastic beanstalk in AWS
  bucket_path: "docker-react" # will be app name by default, it will be generated when you first deploy
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY