version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - /app/node_modules
      - .:/app # map the current folders outside the container to the 'app' folder inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true # to make react see the changes done automatically
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    environment:
      - CHOKIDAR_USEPOLLING=true